POST http://localhost:4400/employee/register
Content-Type: application/json

{
    "name": "Daniel Kitheka",
    "email": "dankinyi99@gmail.com",
    "phone_no": "0767876562",
    "id_no": 633784563,
    "KRA_PIN": "ADjCC32XXY3",
    "NHIF_NO": "119z0784J43",
    "NSSF_NO": "kdhu787n9DS",
    "password": "12345678"
}


### add notes
POST http://localhost:4400/note/addNote
Content-Type: application/json

{
    "email": "dankinyi99@gmail.com",
    "password": "12345678"
}

### fetching notes
GET http://localhost:4400/notes/
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6IjBhZGJiM2I1LWRlYWQtNDQ4Zi05Y2ExLTQ0ZjkzZDBlNTUyNyIsIm5hbWUiOiJKYW5lIERvZSIsImVtYWlsIjoiamFuZUB5b3BtYWlsLmNvbSIsInJvbGUiOiJlbXBsb3llZSIsImlhdCI6MTY5ODgyNjA3NywiZXhwIjoxNjk4ODI5Njc3fQ.SWJpmBD3z6n4cyeBupF5kGmuZwGGptMB3ragM_rN1rI


### checking user details
GET http://localhost:4400/employee/check_user_details
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6IjBhZGJiM2I1LWRlYWQtNDQ4Zi05Y2ExLTQ0ZjkzZDBlNTUyNyIsIm5hbWUiOiJKYW5lIERvZSIsImVtYWlsIjoiamFuZUB5b3BtYWlsLmNvbSIsInJvbGUiOiJlbXBsb3llZSIsImlhdCI6MTY5ODgyNjA3NywiZXhwIjoxNjk4ODI5Njc3fQ.SWJpmBD3z6n4cyeBupF5kGmuZwGGptMB3ragM_rN1rIy